Form/Entityのテストを追加しました。
nablarch/nablarch-example-batch pull request #41
Opened 2023-08-25 14:27 UTC by chupaaaaaaan

2023-08-28 06:57 UTC, kumagoro1202 requested changes
testBeanValidationシート使ってないなら消してください。

2023-08-28 06:57 UTC, kumagoro1202 commented on src/test/java/com/nablarch/example/app/batch/util/ExampleCharacterSet.java
> +            + IBM_EXTENDED_CHARS;
制限文字というのはどういう意味ですか？名前から役割がわからないです。

2023-08-28 09:48 UTC, chupaaaaaaan commented
https://github.com/nablarch/nablarch-example-batch/pull/41#pullrequestreview-1597571439
削除しました。

2023-08-28 10:02 UTC, chupaaaaaaan commented on src/test/java/com/nablarch/example/app/batch/util/ExampleCharacterSet.java
> +            + IBM_EXTENDED_CHARS;
「文字種を制限しているドメインでは使用不可、制限していないドメインでは使用可」の意図でしたが、わかりにくいので「使用不許可文字」としました。

2023-08-30 01:42 UTC, kumagoro1202 approved these changes

2023-08-30 02:06 UTC, merged